# Generated by Django 6.0.4 on 2026-04-28 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppDevice",
            fields=[
                ("device_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("device_uuid", models.UUIDField(unique=True)),
                ("device_name", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField()),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "app_device",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AppUser",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("full_name", models.TextField()),
                ("role_code", models.CharField(max_length=30)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("is_active", models.BooleanField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "app_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CpiAuditLog",
            fields=[
                ("audit_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("entity_name", models.CharField(max_length=100)),
                ("entity_id", models.BigIntegerField()),
                ("action_code", models.CharField(max_length=30)),
                ("changed_at", models.DateTimeField()),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "cpi_audit_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CpiCollectionItem",
            fields=[
                (
                    "collection_item_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("spec_name", models.TextField(blank=True, null=True)),
                ("spec_type", models.TextField(blank=True, null=True)),
                (
                    "size_value",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("other_spec", models.TextField(blank=True, null=True)),
                ("product_code", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField()),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("item_status", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "cpi_collection_item",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CpiPhoto",
            fields=[
                ("photo_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("local_uuid", models.UUIDField(blank=True, null=True, unique=True)),
                ("file_name", models.TextField()),
                ("file_path", models.TextField()),
                ("mime_type", models.TextField(blank=True, null=True)),
                ("file_hash", models.TextField(blank=True, null=True)),
                ("photo_type", models.CharField(blank=True, max_length=30, null=True)),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                ("sync_status", models.CharField(max_length=20)),
                ("server_received_at", models.DateTimeField(blank=True, null=True)),
                ("is_deleted", models.BooleanField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "cpi_photo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CpiReplacement",
            fields=[
                (
                    "replacement_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("local_uuid", models.UUIDField(blank=True, null=True, unique=True)),
                ("new_name", models.TextField(blank=True, null=True)),
                ("new_type", models.TextField(blank=True, null=True)),
                ("new_size", models.TextField(blank=True, null=True)),
                ("new_unit", models.TextField(blank=True, null=True)),
                ("new_brand", models.TextField(blank=True, null=True)),
                ("new_made_in", models.TextField(blank=True, null=True)),
                (
                    "new_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("replacement_status", models.CharField(max_length=20)),
                ("sync_status", models.CharField(max_length=20)),
                ("created_on_device", models.BooleanField()),
                ("server_received_at", models.DateTimeField(blank=True, null=True)),
                ("last_modified_at", models.DateTimeField()),
                ("is_deleted", models.BooleanField()),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "cpi_replacement",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CpiRound",
            fields=[
                ("round_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("survey_year", models.IntegerField()),
                ("survey_month", models.IntegerField()),
                (
                    "round_status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("LOCKED", "Locked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("collection_start_date", models.DateField(blank=True, null=True)),
                ("collection_end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "cpi_round",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CpiVisit",
            fields=[
                ("visit_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("local_uuid", models.UUIDField(blank=True, null=True, unique=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "gps_lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_lon",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "gps_accuracy_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("visit_status", models.CharField(max_length=20)),
                ("sync_status", models.CharField(max_length=20)),
                ("created_on_device", models.BooleanField()),
                ("server_received_at", models.DateTimeField(blank=True, null=True)),
                ("last_modified_at", models.DateTimeField()),
                ("is_deleted", models.BooleanField()),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "cpi_visit",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimAtoll",
            fields=[
                ("atoll_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "atoll_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("atoll_name", models.TextField()),
                ("sort_order", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "dim_atoll",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimBrand",
            fields=[
                ("brand_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("brand_name", models.TextField(unique=True)),
            ],
            options={
                "db_table": "dim_brand",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimCountry",
            fields=[
                ("country_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "iso_code",
                    models.CharField(blank=True, max_length=3, null=True, unique=True),
                ),
                ("country_name", models.TextField(unique=True)),
            ],
            options={
                "db_table": "dim_country",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimIsland",
            fields=[
                ("island_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "island_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("island_name", models.TextField()),
            ],
            options={
                "db_table": "dim_island",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimItem",
            fields=[
                ("item_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "item_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("item_name", models.TextField()),
                ("coicop_code", models.CharField(blank=True, max_length=20, null=True)),
                ("item_group", models.CharField(blank=True, max_length=30, null=True)),
                ("is_active", models.BooleanField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "dim_item",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimOutlet",
            fields=[
                ("outlet_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "outlet_code",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("outlet_name", models.TextField()),
                ("address_text", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("is_active", models.BooleanField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "dim_outlet",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimRegion",
            fields=[
                ("region_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "region_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("region_name", models.TextField()),
            ],
            options={
                "db_table": "dim_region",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimUnit",
            fields=[
                ("unit_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "unit_code",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("unit_name", models.TextField()),
            ],
            options={
                "db_table": "dim_unit",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FactPrice",
            fields=[
                ("price_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("local_uuid", models.UUIDField(blank=True, null=True, unique=True)),
                ("availability", models.CharField(max_length=30)),
                (
                    "observed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "last_month_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("deviation_reason", models.TextField(blank=True, null=True)),
                ("is_outlier", models.BooleanField()),
                ("quote_status", models.CharField(max_length=20)),
                ("sync_status", models.CharField(max_length=20)),
                ("created_on_device", models.BooleanField()),
                ("server_received_at", models.DateTimeField(blank=True, null=True)),
                ("last_modified_at", models.DateTimeField()),
                ("is_deleted", models.BooleanField()),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "fact_price",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SyncBatch",
            fields=[
                (
                    "sync_batch_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("sync_started_at", models.DateTimeField()),
                ("sync_completed_at", models.DateTimeField(blank=True, null=True)),
                ("sync_status", models.CharField(max_length=20)),
                ("records_sent", models.IntegerField()),
                ("records_accepted", models.IntegerField()),
                ("records_rejected", models.IntegerField()),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "sync_batch",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SyncConflictLog",
            fields=[
                ("conflict_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("table_name", models.TextField()),
                ("record_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "conflict_type",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("local_payload", models.JSONField(blank=True, null=True)),
                ("server_payload", models.JSONField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
            ],
            options={
                "db_table": "sync_conflict_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CollectorAssignment",
            fields=[
                (
                    "assignment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="cpi.appuser",
                    ),
                ),
                (
                    "outlet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collector_assignments",
                        to="cpi.dimoutlet",
                    ),
                ),
            ],
            options={
                "db_table": "collector_assignment",
                "unique_together": {("collector", "outlet")},
            },
        ),
    ]
