# Generated by Django 6.0.4 on 2026-05-04 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpi", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cpivisit",
            options={"managed": True},
        ),
    ]
