# Generated by Django 6.0.4 on 2026-06-08 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpi", "0002_alter_cpivisit_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectorItemAssignment",
            fields=[
                (
                    "assignment_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("is_active", models.BooleanField()),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("item_split", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "collector_item_assignment",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CollectorWorkloadSummary",
            fields=[
                (
                    "summary_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("island_name", models.CharField(max_length=100)),
                ("outlet_name", models.CharField(max_length=200)),
                ("total_items", models.IntegerField()),
                ("assignment_type", models.CharField(max_length=50)),
                ("item_split", models.CharField(max_length=50)),
                ("collector_name", models.CharField(max_length=150)),
                ("assigned_items", models.IntegerField()),
                ("is_active", models.BooleanField()),
                ("assigned_date", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Collector Workload Summary",
                "verbose_name_plural": "Collector Workload Summary",
                "db_table": "collector_workload_summary",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimItemGroup",
            fields=[
                (
                    "item_group_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("group_code", models.CharField(max_length=20, unique=True)),
                ("group_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dim_item_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DimOutletType",
            fields=[
                (
                    "outlet_type_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("broad_type", models.TextField()),
                ("outlet_type_name", models.TextField(unique=True)),
            ],
            options={
                "db_table": "dim_outlet_type",
                "managed": False,
            },
        ),
        migrations.AddField(
            model_name="cpivisit",
            name="collector_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cpi.appuser",
            ),
        ),
        migrations.AddField(
            model_name="cpivisit",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cpi.appdevice",
            ),
        ),
        migrations.AddField(
            model_name="cpivisit",
            name="gps_distance_meters",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="cpivisit",
            name="gps_recorded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpivisit",
            name="gps_within_range",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cpivisit",
            name="outlet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cpi.dimoutlet",
            ),
        ),
        migrations.AddField(
            model_name="cpivisit",
            name="round",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="cpi.cpiround",
            ),
            preserve_default=False,
        ),
    ]
