# Generated by Django 6.0.4 on 2026-06-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpi", "0003_collectoritemassignment_collectorworkloadsummary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpivisit",
            name="review_status",
            field=models.CharField(default="PENDING_REVIEW", max_length=30),
        ),
        migrations.AddField(
            model_name="cpivisit",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
