# Generated by Django 6.0.4 on 2026-07-19 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpi", "0004_cpivisit_review_status_cpivisit_reviewed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="CpiBasket",
            fields=[
                ("basket_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("basket_code", models.CharField(max_length=50)),
                ("level", models.IntegerField(blank=True, null=True)),
                ("coicop_2016", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField()),
                ("is_basket_item", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(blank=True, null=True)),
                (
                    "coicop_division_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("coicop_division_name", models.TextField(blank=True, null=True)),
                (
                    "coicop_group_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("coicop_group_name", models.TextField(blank=True, null=True)),
                (
                    "coicop_class_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("coicop_class_name", models.TextField(blank=True, null=True)),
                (
                    "coicop_subclass_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("coicop_subclass_name", models.TextField(blank=True, null=True)),
                (
                    "basket_item_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("basket_item_name", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cpi_basket",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CpiMethodology",
            fields=[
                (
                    "methodology_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("methodology_code", models.CharField(max_length=20, unique=True)),
                ("methodology_name", models.CharField(max_length=200)),
                (
                    "survey_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "survey_period",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                (
                    "basket_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "index_reference_period",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("index_base", models.IntegerField(default=100)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                (
                    "methodology_status",
                    models.CharField(default="DRAFT", max_length=20),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "cpi_methodology",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CpiWeight",
            fields=[
                ("weight_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("weight_value", models.DecimalField(decimal_places=8, max_digits=18)),
                (
                    "weight_reference_period",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cpi_weight",
            },
        ),
        migrations.DeleteModel(
            name="DimItem",
        ),
        migrations.DeleteModel(
            name="DimItemGroup",
        ),
        migrations.AlterModelOptions(
            name="appuser",
            options={},
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="collectorassignment",
                    name="round",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="round_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlet_assignments",
                        to="cpi.cpiround",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name="collectorassignment",
                    constraint=models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("round", "outlet"),
                        name="uq_collector_assignment_active_round_outlet",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cpiweight",
            name="basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="weights",
                to="cpi.cpibasket",
            ),
        ),
        migrations.AddField(
            model_name="cpiweight",
            name="methodology",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="weights",
                to="cpi.cpimethodology",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cpiweight",
            unique_together={("methodology", "basket")},
        ),
    ]
