# Generated by Django 6.0.4 on 2026-07-19 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cpi",
            "0005_cpibasket_cpimethodology_cpiweight_delete_dimitem_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        # Update Django's migration state only.
        # The old database constraint is already absent.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="collectorassignment",
                    unique_together=set(),
                ),
            ],
        ),

        # These old columns are already absent from app_user.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="appuser",
                    name="role_code",
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="appuser",
                    name="username",
                ),
            ],
        ),

        # This column does not yet exist, so create it normally.
        migrations.AddField(
            model_name="appuser",
            name="assigned_island",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="cpi.dimisland",
            ),
        ),

        # The following columns already exist in the database.
        # Add them only to Django's migration state.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="appuser",
                    name="django_user",
                    field=models.OneToOneField(
                        blank=True,
                        db_column="django_user_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cpi_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="appuser",
                    name="email",
                    field=models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                    ),
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="appuser",
                    name="role",
                    field=models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Administrator"),
                            (2, "Supervisor"),
                            (3, "Collector"),
                            (4, "Viewer"),
                        ],
                        default=3,
                    ),
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="appuser",
                    name="updated_at",
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
        ),

        # These fields already exist, and full_name is used by a database view.
        # Update Django's state without issuing ALTER TABLE statements.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="appuser",
                    name="created_at",
                    field=models.DateTimeField(auto_now_add=True),
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="appuser",
                    name="full_name",
                    field=models.CharField(max_length=200),
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="appuser",
                    name="is_active",
                    field=models.BooleanField(default=True),
                ),
            ],
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="appuser",
                    name="user_id",
                    field=models.BigAutoField(
                        db_column="user_id",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
    ]