# Generated by Django 6.0.4 on 2026-07-22 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cpi", "0006_alter_collectorassignment_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CpiItemPhoto",
            fields=[
                ("photo_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "photo_category",
                    models.CharField(
                        choices=[
                            ("ITEM", "Item Photo"),
                            ("REPLACEMENT", "Replacement Photo"),
                        ],
                        default="ITEM",
                        max_length=20,
                    ),
                ),
                ("photo", models.ImageField(upload_to="cpi/item_photos/%Y/%m/")),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="cpi.cpicollectionitem",
                    ),
                ),
                (
                    "replacement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="cpi.cpireplacement",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_item_photos",
                        to="cpi.appuser",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_photos",
                        to="cpi.cpivisit",
                    ),
                ),
            ],
            options={
                "db_table": "cpi_item_photo",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("replacement__isnull", True)),
                        fields=("collection_item", "visit", "photo_category"),
                        name="unique_item_photo_per_visit",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("replacement__isnull", False)),
                        fields=("replacement", "photo_category"),
                        name="unique_replacement_photo",
                    ),
                ],
            },
        ),
    ]
