# Generated by Django 6.0.4 on 2026-07-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cpi", "0007_cpiitemphoto"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cpiitemphoto",
            name="unique_item_photo_per_visit",
        ),
        migrations.RemoveConstraint(
            model_name="cpiitemphoto",
            name="unique_replacement_photo",
        ),
        migrations.DeleteModel(
            name="CpiItemPhoto",
        ),
    ]
